### ISSUE TITLE
Put a condition if he has attendance below 75 percent but he has medical certificate than he is allowed to enter the class and make all the input as user input

### ISSUE THREAD

**Issue by dscgecbsp** [dscgecbsp/Attendence-Program-Using-Python-Hacktoberfest-2022#2]

**Comment by MISSIC17** [comment]
assign me. I am supposed to write it in the attendance program file right?

**Comment by Aksbj** [comment]
Hello Sir, Can you assighn this code to me?

**Comment by dscgecbsp** [comment]
I assighn this issue to you @Aksbj

**Comment by Ash0069** [comment]
Hi @dscgecbsp, please assign this issue to me if still available

**Comment by dscgecbsp** [comment]
I assighn this issue to you @Ash0069

**Comment by dscgecbsp** [comment]
I assign this issue to you @AmruthaSri852

**Comment by prakriti0903** [comment]
please assign this issue to me @dscgecbsp

**Comment by swikrit92** [comment]
please assign this issue to me @dscgecbsp

**Comment by Deeptan2002** [comment]
pls assign this issue to me @dscgecbsp

**Comment by Vikas-sr001** [comment]
please assign this issue to me @dscgecbsp

**Comment by mohnishjamde** [comment]
Please assign issue to me.

**Comment by dscgecbsp** [comment]
i assighn this issue to you @Deeptan2002

**Comment by dscgecbsp** [comment]
i assighn this issue to you @swikrit92

**Comment by dscgecbsp** [comment]
i assighn this issue to you @mohnishjamde

**Comment by Sparsh0211** [comment]
please assign this issue to me @dscgecbsp

**Comment by roshniyadav12** [comment]
Please assign this issue to me @dscgecbsp

**Comment by MuskanVerma11** [comment]
Please assign this issue to me @dscgecbsp

**Comment by adiiiiittyya** [comment]
Please assign this issue to me @dscgecbsp

**Comment by dscgecbsp** [comment]
i assign this issue to @Sparsh0211

**Comment by dscgecbsp** [comment]
I assign this issue to @Hema0825

**Comment by Ashutosh11-yadav** [comment]
please assign this issue to me @dscgecbsp

**Comment by dewanganRachna** [comment]
Please assign this issue to me @dscgecbsp

**Comment by kunalsahuu** [comment]
can you please assign this issue to me @dscgecbsp

**Comment by Yashwant711** [comment]
Please assign this issue to me @dscgecbsp
